import { YearConfig } from './CourseByYearSection.types';

export const YEAR_CONFIGS: Record<number, YearConfig> = {
    1: {
        label: 'السنة الأولى',
        headerBg: 'bg-violet-600',
        headerText: 'text-text',
        badgeBg: 'bg-violet-500',
        cardBorder: 'border-border hover:border-violet-200',
        cardAccent: 'hover:bg-violet-50/40',
        dot: 'bg-violet-500',
        codeBg: 'bg-violet-100',
        codeText: 'text-violet-800',
        semesterBg: 'bg-surface-alt',
        semesterText: 'text-violet-600',
        semesterBorder: 'border-border',
    },
    2: {
        label: 'السنة الثانية',
        headerBg: 'bg-sky-600',
        headerText: 'text-text',
        badgeBg: 'bg-sky-500',
        cardBorder: 'border-border hover:border-sky-200',
        cardAccent: 'hover:bg-sky-50/40',
        dot: 'bg-sky-500',
        codeBg: 'bg-sky-100',
        codeText: 'text-sky-800',
        semesterBg: 'bg-surface-alt',
        semesterText: 'text-sky-600',
        semesterBorder: 'border-border',
    },
    3: {
        label: 'السنة الثالثة',
        headerBg: 'bg-emerald-600',
        headerText: 'text-text',
        badgeBg: 'bg-emerald-500',
        cardBorder: 'border-border hover:border-emerald-200',
        cardAccent: 'hover:bg-emerald-50/40',
        dot: 'bg-emerald-500',
        codeBg: 'bg-emerald-100',
        codeText: 'text-emerald-800',
        semesterBg: 'bg-surface-alt',
        semesterText: 'text-emerald-600',
        semesterBorder: 'border-border',
    },
    4: {
        label: 'السنة الرابعة',
        headerBg: 'bg-orange-500',
        headerText: 'text-text',
        badgeBg: 'bg-orange-400',
        cardBorder: 'border-border hover:border-orange-200',
        cardAccent: 'hover:bg-orange-50/40',
        dot: 'bg-orange-500',
        codeBg: 'bg-orange-100',
        codeText: 'text-orange-800',
        semesterBg: 'bg-surface-alt',
        semesterText: 'text-orange-600',
        semesterBorder: 'border-border',
    },
};

export const FALLBACK_CONFIG = {
    label: 'أخرى',
    headerBg: 'bg-slate-600',
    headerText: 'text-text',
    badgeBg: 'bg-slate-500',
    cardBorder: 'border-slate-200 hover:border-slate-300',
    cardAccent: 'hover:bg-slate-50/40',
    dot: 'bg-slate-500',
    codeBg: 'bg-slate-200',
    codeText: 'text-slate-700',
    semesterBg: 'bg-surface-alt',
    semesterText: 'text-text',
    semesterBorder: 'border-border',
};

export const SEMESTER_LABELS: Record<number, string> = {
    1: 'الفصل الأول',
    2: 'الفصل الثاني',
};
