import type { Course } from "@/shared/types/index";

export const NODE_W = 180;
export const NODE_H = 90;
export const H_GAP = 50;
export const V_GAP = 110;

export const UNI_ELECTIVES: Course[] = [
    {
        id: -101,
        sectionId: null,
        name: 'متطلب جامعة اختياري 1',
        course_code: 'UNIELEC1',
        credit_hours: 3,
        is_lab: false,
        course_type: 'uni_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
    {
        id: -102,
        sectionId: null,
        name: 'متطلب جامعة اختياري 2',
        course_code: 'UNIELEC2',
        credit_hours: 3,
        is_lab: false,
        course_type: 'uni_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
    {
        id: -103,
        sectionId: null,
        name: 'متطلب جامعة اختياري 3',
        course_code: 'UNIELEC3',
        credit_hours: 3,
        is_lab: false,
        course_type: 'uni_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
];

export const MAJOR_ELECTIVES: Course[] = [
    {
        id: -201,
        sectionId: null,
        name: 'اختياري تخصص 1',
        course_code: 'MAJELEC1',
        credit_hours: 3,
        is_lab: false,
        course_type: 'major_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
    {
        id: -202,
        sectionId: null,
        name: 'اختياري تخصص 2',
        course_code: 'MAJELEC2',
        credit_hours: 3,
        is_lab: false,
        course_type: 'major_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
    {
        id: -203,
        sectionId: null,
        name: 'اختياري تخصص 3',
        course_code: 'MAJELEC3',
        credit_hours: 3,
        is_lab: false,
        course_type: 'major_elective',
        year: 0,
        semester: 1,
        prerequisites: [],
        past_year_questions: [],
        files: [],
        videos: [],
    },
];
